Repository devcontainers-community/templates, pull requests merged in 2023-04, with the labels that each got.

#10 docs: add contributing guide with conventions docs
  CONTRIBUTING.md
Labels: documentation, help wanted

#9 docs: add content to readme
  README.md
Labels: documentation, enhancement

#5 feat(jupyter-datascience-notebooks): add a new template jupyter-datascience-notebooks
  .github/workflows/test-pr.yaml
  .mega-linter.yaml
  src/jupyter-datascience-notebooks/.devcontainer/Dockerfile
  src/jupyter-datascience-notebooks/.devcontainer/devcontainer.json
  src/jupyter-datascience-notebooks/NOTES.md
  src/jupyter-datascience-notebooks/devcontainer-template.json
  test/jupyter-datascience-notebooks/test.sh
Labels: enhancement

#21 revert: remove construction banner
  README.md
Labels: documentation
